spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none  # или update, если нужна авто-миграция
    properties:
      hibernate:
        show_sql: true
        enable_lazy_load_no_trans: true
        cache:
          use_second_level_cache: false
        temp:
          use_jdbc_metadata_defaults: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
