CREATE TABLE IF NOT EXISTS comment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text,
    post_id bigint REFERENCES post(id) ON DELETE SET NULL

);

CREATE TABLE IF NOT EXISTS tag (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(128) NOT NULL,
    post_id bigint REFERENCES post(id) ON DELETE SET NULL
);

ALTER TABLE IF EXISTS post RENAME COLUMN name TO title;
ALTER TABLE IF EXISTS post RENAME COLUMN "text" TO content;

ALTER TABLE IF EXISTS post ADD COLUMN like_counter bigint default 0;
